### ISSUE TITLE
Error: "HttpError: Resource not accessible by integration" when using github action

### ISSUE THREAD

**Issue by munapower** [wow-actions/spell-checker#2]
### Expected Behavior

Spell checking should be performed on file README.md
### Current Behavior

There is an HTTP Error returned instead
### Possible Solution

Can this be related to this issue https://github.com/octokit/rest.js/issues/32 ? It seems octokit was updated after you published this action
### Steps To Reproduce

1. Create a job with a step that invokes the github action
2. Modify a markdown file
3. Push to repo

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
0s
##[debug]Evaluating condition for step: 'Spell Check'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Spell Check
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run wow-actions/spell-checker@v[1](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:1)
Base commit: 6514d77e896c56076ac3a36614ee75a0cc577[2](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:2)ba
Head commit: 1b6cc0905170110[3](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:3)10db3f92ca[4](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:4)[5](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:5)d7[6](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:6)fd2321cd[8](https://github.com/munapower/fabric-private-chaincode/actions/runs/8024747091/job/21924212467#step:3:8)
##[debug]changed files: [
##[debug]  "README.md"
##[debug]]
checking files: [
  "README.md"
]
Error: HttpError: Resource not accessible by integration
Error: Resource not accessible by integration
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Spell Check

</p></details>

### Your Environment

We have a github action that only runs if the changes are only markdown files. We want to spell check these files. I am testing this on a branch and only made changes to the readme file. Basically added "wong wods foget" to the file to see if the spell checker could catch them.

- x6: [e.g. 1.0.0]
- OS: [e.g. macOS Sierra 10.12.3]
- Browser: [e.g. chrome 78.0.3904.108]
This is my yaml:
```
name: Check Documentation
on:
  push:
    paths:
    - '**.md'
defaults:
  run:
    shell: bash
#permissions: {}
jobs:
  check-md-only:
    name: This job was triggered
    runs-on: ubuntu-latest
    outputs:
      md-only: ${{ steps.test-md-only.outputs.md-only }}
    permissions:
        contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # required to compare HEAD^
    - run: git diff --name-only HEAD^..HEAD
    - name: Test MD only
      id: test-md-only
      run: >-
        [ -z "$(git diff --name-only HEAD^..HEAD | grep -ve "\.md$")" ] &&
        echo "md-only=${{toJSON(true)}}" >> $GITHUB_OUTPUT ||
        echo "md-only=${{toJSON(false)}}" >> $GITHUB_OUTPUT
  build:
    name: Run if only MD files
    needs: ['check-md-only']
    runs-on: ubuntu-latest
    if: ${{ fromJSON(needs.check-md-only.outputs.md-only) == true }}
    steps:
    - run: echo ran
    - name: Spell Check
      uses: wow-actions/spell-checker@v1
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         include: |
            **/*.md
```
